version: 2

sources:
  - name: staging
    database: "{{ env_var('DBT_DATABASE', 'de-zoomcampfire') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'module_04') }}"
      # loaded_at_field: record_loaded_at
    tables:
      - name: green_tripdata_external
      - name: yellow_tripdata_external
      - name: fhv_tripdata_external